### ISSUE TITLE
Use PHP_EOL instead "\n"

### ISSUE THREAD

**Issue by gilbert1995** [fubralimited/php-oara#23]
For exemple, in: Oara\Network\Publisher\CommissionJunction.php
You use at line 150:
```
$cookieArray = explode("\n", $cookieContent);
```

But i'm on a windows server, and windows use "\n\t"

I suggest use PHP_EOL beaucause it detect automaticly.
```
$cookieArray = explode(PHP_EOL , $cookieContent);
```
Sorry for my english

**Comment by cmorillo** [comment]
Hi gilbert,

No worries about your English, we would like to do that but that would require a lot of work on our side, for the moment we won't be able to do that but if you are keen to do it we could add it on the main project for everyone else.

Cheers,

Carlos
