### ISSUE TITLE
TradeTracker

### ISSUE THREAD

**Issue by hassan-kiran** [fubralimited/php-oara#24]
While creating instance for TradeTracker i got error Fatal error: Uncaught exception 'Exception' with message 'No Network Available TradeTracker' .Any help ??

**Comment by cmorillo** [comment]
Hi Hassan,

I hope you are fine, We would need more information to check what your
problem is. That error just means that the network weren't able to be
created or the path wasn't found.

Cheers,

Carlos

2015-03-10 11:30 GMT+00:00 hassan-kiran <notifications@github.com>:

**Comment by hassan-kiran** [comment]
Hi ,
Same code working fine with other networks Amazon ,Daisycon etc. Working on localhost.

Error shows on object creation :

$networkName = "TradeTracker"; 
$config = Zend_Registry::getInstance()->get('credentialsIni');

$configName = strtolower($networkName);
$credentials = $config->$configName->toArray();
$credentials["cookiesDir"] = "example";
$credentials["cookiesSubDir"] = $networkName;
$credentials["cookieName"] = "test";

$credentials['networkName'] = $networkName;
$credentials['type'] = "Publisher";
//The Factory creates the object
<b>$network = Oara_Factory::createInstance($credentials); //On this line only for TradeTracker </b>
Oara_Test::testNetwork($network);

**Comment by hassan-kiran** [comment]
Issue fixed.
User and password are different for web services API and site login.
tradetracker.user = '123 ' // Customer ID  given in     Creative Tools -> Web Services
tradetracker.password = '123' //Passphrase given in Creative Tools -> Web Services

**Comment by royduin** [comment]
Strange it's says `No Network Available TradeTracker` instead of saying that the credentials aren't right. The TradeTracker class contructor fails so it gives this error?

**Comment by cmorillo** [comment]
Probably there is an exeption during the creation of the object. Should be
on the __construct method the issue.

2015-05-23 19:24 GMT+01:00 Roy <notifications@github.com>:

**Comment by royduin** [comment]
Jup, I think the contructor code needs to moved to the `checkConnection()` function and there should be added some error handling. If I find myself some free time I'll fix it and create a pull request.
