### ISSUE TITLE
Extra status, get all transactions from all merchants, extra transaction information and clicks

### ISSUE THREAD

**Issue by royduin** [fubralimited/php-oara#27]
Hi,

Before I'll create a pull request I'd like to discuss these 4 things:

1. Currently there is `CONFIRMED`, `PENDING` and `DECLINED`. For example Zanox does have a `approved` status, this one is different from the `confirmed` status. Approved means; approved by the advertiser but not yet payed. When the bill is payed by the advertiser to the network it will get the status `confirmed`. I'd like to see this extra status, now a lot of transactions stay on `PENDING` and I'd like to see when it's approved by the advertiser. Do you guys agree with this implementation? Not every network does have this extra status...

2. If I'd like to get all the transactions from a network from all the merchants I first have to call the `getMerchantList()` function, map this array with something like:
	```
$merchants = $network->getMerchantList();
foreach($merchants as $merchant){
		$merchantIds[] = $merchant['cid'];
}
```
Then I can pass this array of ID's to the `getTransactionList()` function. This is only needed because of these if statements:
	- Zanox: https://github.com/fubralimited/php-oara/blob/master/Oara/Network/Publisher/Zanox.php#L149
	- Daisycon: https://github.com/fubralimited/php-oara/blob/master/Oara/Network/Publisher/Daisycon.php#L169
	- TradeTracker: https://github.com/fubralimited/php-oara/blob/master/Oara/Network/Publisher/TradeTracker.php#L101

	I think it's much easier to check in the `getTransactionList()` function for the `$merchantList` variable. If this one is `null` or an empty array the `getTransactionList()` function will skip the if statement. That way I don't have to get the merchant list first and I don't have to map that to an array of ID's to get the transactions of all merchants. I didn't checked all the networks, do all networks return all the transactions from all the merchants by default? Do you guys agree with this implementation?

3. Currently the most networks return a `unique id`, `merchant id`, `date`, `status`, `amount` and `commission`. What about some extra fields? I think to most of the networks give more information but that isn't implemented. For example I'd like a `merchant name` (so I don't need the `getMerchantList()` function for this, see my point 2), `media name` (my website name) and the `products` (a description of what was bought). I think these are pretty general fields for all the networks, agree with this implementation?

4. What about clicks? Currently this ins't implemented anywhere but I think it's pretty handy for creating graphs. A new function `getClicksList()`, like the `getTransactionList()` function which returns the amount of clicks per day. I can implement this for some networks...

**Comment by cmorillo** [comment]
Hi Roy,

Sorry for the late reply, quite busy lately.

1. You could create an extra field on the transaction called "extrastatus"
or whatever other name and then use it to get that info. As you said not
all the networks have that information and we tend to unify.

2. There are a lot of more networks that uses this structure, you may not
use them but all of them follow or should follow the merchantID filter
(sometimes we don't have a choice), this will reduce a lot of request and
overhead. My recommendation would be to code this on your endpoint as we do
on AffJet.

Thank you very much for your time to write and imporve php-oara. If you
have any other question let me know.

Cheers,

Carlos

2015-05-31 13:29 GMT+01:00 Roy <notifications@github.com>:

**Comment by royduin** [comment]
@cmorillo, thanks for your reply! So if I implement my first and second point you won't accept the pull request? Because it's a little bit less generic than? What about my other questions?

**Comment by cmorillo** [comment]
Hi Roy,
I hope you are fine, sorry, I replied via phone and didn't see the other two questions:

1. If you do the extra status adding it as a new field I will accept that on a pull request.
2. Is a little pain to do the merchants like this but is the best approach we found so far, also sometimes the network needs the merchantid to get the transactions, such as Affiliate Window, so I think there is no real workaround.
3. You can add as many extra fields as you want, but the core fields (the ones you mention) should stay the same, we just didn't have the need till now to add media fields for example.
4. We did that in the past, getting the number of clicks but just a little number of networks support it and if you have a medium size account it would take a long time to get the info as the API are not ready to give the information in a friendly way.

Cheers,

Carlos

**Comment by royduin** [comment]
When I find myself some free time I'll submit some pull requests, I can extend it in my application but I think it's better to merge it. I'm coming back on this. Thanks for your reply!

**Comment by philhudson91** [comment]
+1 for 1. pending and confirmed need to be clearly defined.

**Comment by royduin** [comment]
@philhudson91, for which network do you need this? I've already done it for Zanox, see the accepted commit in the pull request: https://github.com/royduin/php-oara/commit/27eff6d35e3d987f7572b08342a290fc034b0a84

**Comment by cmorillo** [comment]
Yes, if you need any other status just added it up and I will review it and probably add it.
