### ISSUE TITLE
Composer fail

### ISSUE THREAD

**Issue by pvdbroek** [fubralimited/php-oara#32]
Hi!

When I try to install using composer, I'm getting the following error:

------------------------------------------------------------------------
Your requirements could not be resolved to an installable set of packages.

Problem 1
 - Installation request for fubralimited/php-oara dev-master -> satisfiable by fubralimited/php-oara[dev-master].
 - fubralimited/php-oara dev-master requires google/apiclient dev-master -> no matching package found.

------------------------------------------------------------------------

Looks like the package "google/apiclient" does not exist (anymore). Would it be possible to fix this?

Thanks!

Pim

**Comment by pvdbroek** [comment]
Hi @cmorillo , did you have time to look at this issue?

Many thanks!

Pim

**Comment by cmorillo** [comment]
Hi Pim,

I have just installed it using this instructions and it works:

https://github.com/fubralimited/php-oara

Are you using php-oara in any other project using composer?

2015-07-06 9:19 GMT+01:00 Pim <notifications@github.com>:

**Comment by pvdbroek** [comment]
Hi,

thanks for your response!

I want to use php-oara in an existing laravel 5 project, so I added:

        "fubralimited/php-oara": "dev-master"

to the "require" part in composer.json.

But this results in the error above. Am I doing anything wrong? Should I add "google/apiclient" or something similar as well?

Regards,

Pim

**Comment by cmorillo** [comment]
if you are using it under another composer project, yes, you will need to
re-add the libraries so they are on the path, zend, google,etc...

2015-07-06 16:36 GMT+01:00 Pim <notifications@github.com>:

**Comment by pvdbroek** [comment]
Ah, you are the best! Thanks for taking the time for explaining it to me and of course, for creating this package :+1:

**Comment by cmorillo** [comment]
No problem, pleasure :)

2015-07-06 16:49 GMT+01:00 Pim <notifications@github.com>:
