### ISSUE TITLE
Remove Zend dependency

### ISSUE THREAD

**Issue by kusmierz** [fubralimited/php-oara#36]
Hello, maybe it will be good idea to remove whole Zend Framework dependency? Or at least to use individual packages from Zend2, that means only few really needed classes (Soap, HttpClient)? By now, it's almost 100M of code, which php-oara uses only few files...

My suggetions (I've found only those Zend_* classes):
- Zend_Date => php's DateTime, or [briannesbitt/carbon](https://github.com/briannesbitt/carbon) or [fightbulc/moment.php](https://github.com/fightbulc/moment.php); and if required - [thephpleague/period](https://github.com/thephpleague/period)
- Zend_Http_Client and Zend_Soap => [zendframework/zend-soap](https://github.com/zendframework/zend-soap) and [zendframework/zend-http](https://github.com/zendframework/zend-http) or something even smaller like http://sourceforge.net/projects/nusoap/, 
- Zend_Filter_LocalizedToNormalized => [sebastianbergmann/money](https://github.com/sebastianbergmann/money) or [mathiasverraes/money](https://github.com/mathiasverraes/money)
- Zend_Dom_Query => https://github.com/paquettg/php-html-parser, https://github.com/FluentDOM/FluentDOM, https://github.com/tj/php-selector

**Comment by karptonite** [comment]
I second this. I like this package, but requiring all of the Zend Framework for just a few tools seems excessive.

**Comment by paulmaunders** [comment]
Feel free to make these changes and send a pull request :)

**Comment by cmorillo** [comment]
We are working on a second version for php oara free of zend dependencies, on test as we speak
