### ISSUE TITLE
Amazon Affiliate connector does not work

### ISSUE THREAD

**Issue by alex94040** [fubralimited/php-oara#45]
At least two issues discussed in this pull request: https://github.com/fubralimited/php-oara/pull/41

1) Connection check (fixed by #41)
2) Getting this error when downloading transactions for the US Amazon affiliate account, after I apply the pull request #41. 

Notice: Undefined offset: 5 in ~/php-oara/Oara/Network/Publisher/Amazon.php on line 359

When I tried some simple print_r statements for debugging, $transactionExportArray is empty.

**Comment by cmorillo** [comment]
duplicated #47
