### ISSUE TITLE
Country Code For India

### ISSUE THREAD

**Issue by CHANDRA-BHUSHAN-SAH** [fubralimited/php-oara#50]
Hello,
I want to try this library for amazon India affiliate network. So, whether it work for Amazon India or Not, if yes then how it can be used and what country code I should use to make it working?
Thanks.

**Comment by cmorillo** [comment]
You will need credentials for https://assoc-datafeeds-eu.amazon.com/datafeed/listReports, please contact your support on Amazon about this.
