### ISSUE TITLE
How do you handle transactions from merchants that are no longer active ?

### ISSUE THREAD

**Issue by hammat** [fubralimited/php-oara#66]
Hi,
First thanks for the interface provided !

I'm facing an issue with transactions that are excluded because they're from a merchant I'm not working with anymore. Let me explain : back in 2015, I've been accepted on a merchant and we worked together for some times before our partnership ended.

When I try to fetch transactions from this time, they are excluded because the merchant is not in the _getMerchantList_ results anymore. The network here in my example is Effiliation. _getMerchantList_ is filtering with _active_ merchants. If I filter with _all_, then transactions are fetched correctly.

Is there a reason to only use active merchants ? Should we have a parameter to choose if we want active / inactive / refused / all (for example) ?

Thanks for your feedback !

**Comment by cmorillo** [comment]
Hi @hammat , the reason behind it is that Networks usually have thousand of them, what we do on AffJet is store them and just add new ones so we historically have just the ones we have used.

As on the transaction function you will need to pass the merchants Id , if you import them all you will end up with thousands of queries with no results. So merchanList must be getMerchantList + Historic Merchant on DB.

I hope that makes sense
